# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5221e0164ac1bc3b2c2924534897d620cb5805ca7555bd01b171f62d7159a518351483691b15c445f4f491bd48f44568e9e5e3cf4849fa9c7d173cba3222fffc

test:
  secret_key_base: 1c3d77bf57a12f48a7b0cff4b73ad4611594bd5f5de435fc59ab58492e59a06fec35fc4aecff7f41c9b35531e98bdc7ef153c09d5e6542eb03ca425c8801451d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
